### ISSUE TITLE
Minor issue on GitHub readme (links = 404)

### ISSUE THREAD

**Issue by parfish** [beakerbrowser/unwalled.garden#20]
Just a minor housekeeping issue:
https://github.com/beakerbrowser/unwalled.garden

On the README.md

> Governance
> 
> The rules for governance are as follows:
> 
>     Open **issues** or **pull requests** to discuss changes, problems, and ideas.
The "issue" and "pull request" links get a 404:
https://github.com/beakerbrowser/unwalled.garden/blob/develop/issues
https://github.com/beakerbrowser/unwalled.garden/blob/develop/pulls

P.

**Comment by pfrazee** [comment]
Whoops, thanks!
