### ISSUE TITLE
"omni" post array

### ISSUE THREAD

**Issue by danimesq** [beakerbrowser/unwalled.garden#35]
It points in which other networks the same post is baked, as example:

"omni":[{"url":"dat://6e96b27838c76991ac3563f729beb7c6e6c362fe369793784cd1c729b2b37299","net":"Namecoin"},{"url":"dat://6348fac3c70e916885ead7dce6927f01e02c0efd1a9273849891c23b7e7bac4d","net":"Peepeth"},{"url":"dat://c6e05a8a2924b148e60c6b2aab4d8d7fe3a923a14a13ab22119e8d13afd2baf7","net":"ZeroMe"},{"url":"dat://71b4951cd41b604bff8b6ceb6841d0364b7342afe6fbf0319627c84dc1067015","net":"Mastodon"}]

Already used in some posts on Fritter.

**Comment by pfrazee** [comment]
I'd suggest doing this via an extension for now.

**Comment by danimesq** [comment]
@pfrazee
> I'd suggest doing this via an extension for now.

How it would work?
It is done by other file?

**Comment by pfrazee** [comment]
https://unwalled.garden/docs/how-to-extend-schemas
