### ISSUE TITLE
Switch between multiple identities with multiple `Person` schema files?

### ISSUE THREAD

**Issue by trosel** [beakerbrowser/unwalled.garden#38]
Can we switch between multiple accounts by having multiple `person` schema files?

**Comment by pfrazee** [comment]
This is handled by using multiple dat sites, one for each identity. The next Beaker will have this built in

**Comment by trosel** [comment]
>The next Beaker will have this built in

Is this part of the huge 0.9 update that's coming this summer?

**Comment by pfrazee** [comment]
Yep
