### ISSUE TITLE
RSS compatibility 

### ISSUE THREAD

**Issue by trosel** [beakerbrowser/unwalled.garden#42]
Someone will be much more likely to move their blog to UG if RSS works with it. For example, it's not much of an effort to ask readers to switch their RSS URLs. Readers still get linked to your content via their feed readers etc.

Both RSS and ActivityPub are not built with resiliency in mind, so dat is a perfect compliment to it.

Similar to https://github.com/beakerbrowser/unwalled.garden/issues/19 with ActivityPub, I suppose the solution would be to build a service that converts the schemas.

It would be more adoption friendly to do this automatically upon post creation, but perhaps this would be a service more in the domain of the dat service that converts your dat site to an https site.

**Comment by pfrazee** [comment]
RSS compatibility is actually pretty straight-forward. The network model is exactly the same and all you need is a parser for the format. That said, UG's "Post" is very different than the kind of content used for RSS so I wouldn't recommend duplicating content between them. I'd say UG and RSS can work side-by-side.
